### ISSUE TITLE
Admin should be able to see the submitted abstracts in the CFP dashboard

### ISSUE THREAD

**Issue by bitemyapp** [lorepub/moot#13]
No blinding for this flow, strictly restrict access to it.

Tabular dashboard.

See how many abstracts there are.

**Comment by bitemyapp** [comment]
The admin edited version might need to be a historical layer on top of the original just in case something gets fat-fingered. An email notification would preserve the data as well but this is worth thinking about.

**Comment by tdietert** [comment]
I'll take this one.

A few high level questions before I start:
- What do you mean by tabular dashboard?
    My assumption would be to display the abstracts as [Username, Title, Description preview]
- What delineates a "draft" submission vs "completed" abstract? 
    Lack of form field completion? Should we show these in different tabs?
- Should clicking on an abstract take the Admin to an Abstract View, where the admin is viewing a single  abstract in it's full form?
   If so, _this_ is the view that I would enable the Admin editing feature

I'll add more questions as comments as I go along, if I have any.

TODO:
- [ ] Add CFP dashboard route (view) `/conference/<id>/cfp` accessible by Admins of the conference
- [ ] Add table showing all abstracts in DB associated with the conference in the CFP view
- [ ] Separate draft submissions from completed abstracts
- [ ] Add filter-by drop down widget
- [ ] Add sort-by drop down widget
- [ ] Add button to download currently displayed abstracts as CSV
- [ ] Add ability for admins to edit fields of the abstract (in a separate view? new table for edits).

**Comment by bitemyapp** [comment]
>What do you mean by tabular dashboard?

I mean rows and columns showing the data. Probably in the form of an HTML table. May want to add filters and other things but doesn't have to happen on a first pass.

>What delineates a "draft" submission vs "completed" abstract?

Abstract submission isn't done yet, but speakers should have the ability to save a draft versus submitting a final abstract.

>Should clicking on an abstract take the Admin to an Abstract View, where the admin is viewing a single abstract in it's full form?

Yes, but that doesn't need to be included in a first pass of this feature.

**Comment by tdietert** [comment]
Great, thanks!

**Comment by bitemyapp** [comment]
Thank you @tdietert!
