### ISSUE TITLE
Conference dashboard view

### ISSUE THREAD

**Issue by bitemyapp** [lorepub/moot#29]
Should let a person whose account is an owner, admin, or editor see the dashboard for a particular conference. Different links might be shown based on role type but we won't know precisely what that looks like yet.

Cf. 

```haskell
/conference/#Int64                ConferenceDashboardR GET
```

in `src/Routes.hs`

**Comment by tdietert** [comment]
I'll take this on and #28.

**Comment by tdietert** [comment]
This should be closed because of #35
