### ISSUE TITLE
Call for Proposals (CFP) Dashboard for Admin

### ISSUE THREAD

**Issue by tdietert** [lorepub/moot#36]
* This is an Administrator View; It should require and Admin role associated with the user requesting the page.

Admins should have a _Call for Proposals_ dashboard for each conference they are an administrator of (are Admin users administrators for all conferences, or just some?)

The CFP dashboard view should be reachable from the Conference Dashboard view.

It should display all the submitted abstracts for the CFP in a list format, displaying the user that submitted the abstract, and the title of the abstract (sortable?). Clicking an item in this list should take the Admin to the Abstract View.

**Comment by tdietert** [comment]
This should go under the CFP milestone.

**Comment by bitemyapp** [comment]
This is https://github.com/lorepub/moot/issues/13
