### ISSUE TITLE
Signup page separate of abstract submission

### ISSUE THREAD

**Issue by bitemyapp** [lorepub/moot#44]
Don't take this for now, I need to review this.

**Comment by joelmccracken** [comment]
This is the issue that I couldn't find recently.

**Comment by bitemyapp** [comment]
@joelmccracken Thanks :)

**Comment by joelmccracken** [comment]
oh, is this complete? I thought this ticket was about having a totally separate "sign up/register" page, one that is not embedded in the abstract submission interface.

**Comment by joelmccracken** [comment]
ok!
