### ISSUE TITLE
Add ability for admins to edit fields of submitted abstracts

### ISSUE THREAD

**Issue by bitemyapp** [lorepub/moot#47]
In a separate view after clicking the abstract in the dashboard listing, not in-place.

This should probably heed admin-edited vs. user-submitted content. Ask me if you aren't familiar with this distinction.

**Comment by joelmccracken** [comment]
I think i saw that you implemented this; is that correct/is there anything else to this?

**Comment by bitemyapp** [comment]
I think it's good enough for now.
