### ISSUE TITLE
Running `DevelMain.update` crashes ghci on Windows 10 x64

### ISSUE THREAD

**Issue by bitemyapp** [lorepub/moot#67]
```
[23 of 24] Compiling Application      ( C:\Users\callen\work\moot\src\Application.hs, interpreted )
[24 of 24] Compiling DevelMain        ( app\DevelMain.hs, interpreted )
Ok, 24 modules loaded.
*DevelMain> update
make: *** [ghci] Error 127
```

Any Windows users seen this before?

Repro is:

```
make ghci
:l app/DevelMain.hs
update
```

**Comment by bitemyapp** [comment]
Weird. `yesod devel` worked.

**Comment by hstk** [comment]
Running W10 x64 1803, couldn't reproduce.
```
stack ghci moot:lib --ghci-options='-j4 +RTS -A128m'
...
[27 of 27] Compiling DevelMain        ( app\DevelMain.hs, interpreted )
Ok, 27 modules loaded.
*DevelMain> update
Devel application launched: http://localhost:3000
```

**Comment by Truedrog** [comment]
sorry for bumping old thread, but I can reproduce it on Win 10 x64. update func is crashing ghci

And it seems that it crashes on `loadYamlSettings [configSettingsYml] [] useEnv`


```
stack ghci
settings <- loadYamlSettings [configSettingsYml] [] useEnv :: IO AppSettings

*nothing happens then it silently crashes* 
```

**Comment by bitemyapp** [comment]
I don't really develop on Windows and the scaffold here is pretty standard. Can anyone reproduce this issue on a different Yesod project on Windows or is it particular to Moot?

**Comment by Truedrog** [comment]
Yes.
https://github.com/Truedrog/reproymlconfig

If I try to run appmain in ghci it will crash.
I think it’s a bug in ghci on windows.

**Comment by bitemyapp** [comment]
I think you need to report this on the GHC bug tracker, this is out of scope for Moot and Moot is a temporarily moribund project that I may pick up later if others haven't made head-way.

Thank you for reporting it and making the repro. I suggest raising it here: https://gitlab.haskell.org/ghc/ghc/-/wikis/report-a-bug

Closing this as a wontfix.
