### ISSUE TITLE
Compile error in Views.hs

### ISSUE THREAD

**Issue by plaeremans** [lorepub/moot#96]
`moot/src/Helpers/Views.hs:14:28: error:
    Variable not in scope: css_app_css :: Route Static
   |
14 |     addStylesheet (StaticR css_app_css)
   |                            ^^^^^^^^^^^

`

Do not now whether this is a good place to post this, just wanted to play around with yesod example.

**Comment by bitemyapp** [comment]
>Variable not in scope: css_app_css :: Route Static

This means you need to compile the frontend assets, not delete the frontend asset pipeline dependencies.
